#!/usr/bin/env bash
# Install a pre-push hook that scrubs for personal hostnames + private IPs +
# Claude artifacts + secret patterns before allowing a push. Idempotent.
#
# Pattern list is base64-encoded below so the literal strings (e.g. personal
# hostnames) never appear verbatim in this tracked file — otherwise the hook
# itself would block pushes of this installer.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
HOOK=".git/hooks/pre-push"

# Base64-encoded newline-separated list of regex patterns.
# Decode + inspect with: echo "$PATTERNS_B64" | base64 -d
PATTERNS_B64='Um9jaW5hbnRlCkdhbmRhbGYKSG9nd2FydHMKMTkyXC4xNjhcLjRcLlswLTldezEsM30K'

cat > "$HOOK" <<HOOK_EOF
#!/usr/bin/env bash
# content-guard pre-push hook (generated by scripts/install-content-guard.sh)
set -euo pipefail

remote="\$1"
url="\$2"

# Decode the pattern list. Each line is an extended-regex pattern.
PATTERNS_B64='${PATTERNS_B64}'
mapfile -t patterns < <(echo "\$PATTERNS_B64" | base64 -d)

while read local_ref local_sha remote_ref remote_sha; do
  if [[ "\$local_sha" = "0000000000000000000000000000000000000000" ]]; then
    continue
  fi
  if [[ "\$remote_sha" = "0000000000000000000000000000000000000000" ]]; then
    range="\$local_sha"
  else
    range="\$remote_sha..\$local_sha"
  fi

  for pat in "\${patterns[@]}"; do
    if git rev-list "\$range" -- 2>/dev/null | xargs -r -I{} git show {} 2>/dev/null | grep -E "\$pat" > /dev/null; then
      echo "content-guard: push BLOCKED -- pattern '\$pat' appears in commits being pushed"
      echo "  fix: rewrite history with git filter-repo, or revert the offending commit"
      exit 1
    fi
  done
done

exit 0
HOOK_EOF

chmod +x "$HOOK"
echo "installed content-guard hook at $HOOK"
